### ISSUE TITLE
pino logger deprecation issue

### ISSUE THREAD

**Issue by xkeshav** [w3cj/hono-open-api-starter#3]
First of All Thank you very much for the awesome video tutorial.
 
 while was going and rsetructuring up my hono server and learnt many good things. that [pino-logger thing](https://www.youtube.com/watch?v=sNh9PoM9sUE&t=22m); I was tring but it is giving deprectaion error

can you help what changes I requires  the pino-logger.ts file in order to work it well in production also.

![image](https://github.com/user-attachments/assets/a7d2a46f-132a-407c-9efa-aa871a390dbd)

**Comment by w3cj** [comment]
Thanks for letting me know! This error just means that you need to import it as `pinoLogger` now instead of `logger`:

```diff
-import { logger } from "hono-pino"
+import { pinoLogger } from "hono-pino"
```

I will update the template soon to reflect.

On another note, pino does a lot of node.js specific things, so I've been looking into another library [logtape](https://logtape.org/) that support other runtimes, not just node.js - eventually I might add a built in middleware to stoker that uses logtape and then we can remove the dependency on pino.

**Comment by xkeshav** [comment]
looking forward how to use logtab; I have tried below ( which might be not correct.

### middlewares/configure-tap-log.ts
```ts
import { configure, getConsoleSink, getLogger } from "@logtape/logtape";

await configure({
  sinks: { console: getConsoleSink() },
  loggers: [{ category: "my-app", level: "debug", sinks: ["console"] }]
});

export default function loggerTap() { 
  return getLogger(["my-app"])
}
```

and later

```ts
  app.use("*", loggerTap());
```

but it gived typing issue ( which is because AppBindings belongs to pinoLogger ) but what are for this logger.

here is screenshot whicch also throw warning in terminal too.

![image](https://github.com/user-attachments/assets/1e9d9e94-d683-472d-acfd-979f4d33b48f)
